### ISSUE TITLE
Content: Sheds: Doors: Labels

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#154]
top photo: French swing
middle photo: Sliding glass
add photo of single swing door and label: Single full light

Description needs to say something to the effect that we use professional, brand-name doors and windows from Codel, Ply Gem, Andersen and Milgard

**Comment by ckillorin** [comment]
@ModernShed - the idea with this section is to give a broad range of door categories rather than call out a specific item (as depicted). So, our thought is to keep the "categories" broad and add specific items depicted as call outs in the descriptive copy on the far right. That said, do "traditional" and "sliding" make the most sense? Should we change "traditional" to "swing?"

We can add brand names to the section copy at the top left under "Doors"

**Comment by ModernShed** [comment]
Yes, change "traditional" to "French"
