### ISSUE TITLE
Feature: Contact

### ISSUE THREAD

**Issue by ModernShed** [designbyparker/ModernShed#159]
Contact and Download catalog:
see email from Mprobach.
Find a dealer needs to be integrated with the Contact /Inquire page, not a little link at the bottom of a page. And requires zip code and link to the db.
To download the catalog for the "Considering" and "I'm ready" categories, must include the Approximate completion date desired, and size.. or whatever we want to call that piece. included.

**Comment by ckillorin** [comment]
For context, this is the email Tim sent from Mike:

> One of the main purposes/reasons for the web site (in my opinion) is to gather contact info about the lead.  This includes  location of project, time frame, use of studio and contact info.
> 
>  
> 
> With this said – the prospect/lead should still be asked/requested to provide this above info to us if they want to download the catalog.  The “star/button” for the catalog or whatever you call it should be very visible in several locations of the site – including the opening page.  Just having a tab at the bottom is not sufficient enough to catch the leads attention.  Again – it’s all about getting the lead!
> 
>  
> 
> All My Best – All The Time
> 
>  
> 
> “Modern-Mike” Probach
> 
> Modern-Shed Regional Manager
> 
> (206) 295-2557  - Direct Line

**Comment by ckillorin** [comment]
Hey @ModernShed - 

To clarify, the find a dealer feature doesn't capture that information from the user, it just uses it to pull the nearest dealer from your database. That's how it currently functions on your site, as well. Navigating the user flow of the contact form, we're asking them to make a lot of progressive decisions with the goal of capturing the lead. So, incorporating a passive option such as finding a dealer, in the middle of pulling them through the contact form ultimately felt wrong. That's why we opted to include it in the menu and footer. It's also functionally challenging to have a separate form for the zip code/find a dealer feature embedded in the contact form. At the end of the day, since the goal is to get you more qualified leads, we thought this was the best solution.

Also, noted on Mike's feedback about including location, timeframe, use and contact info for the catalogue download. We'll make those fields required.

**Comment by ModernShed** [comment]
Caity.. I get it.. but what if we put “find a design pro” (instead of dealer) here:

 



 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by ModernShed** [comment]
I talked to all the sales reps regarding the find a dealer portion.

1.	When a person wants to connect with us, they will go to the “Contact” page. I think we can all agree upon that.
2.	When you go to Contact, there is NO phone #, no email address, no mailing address and no way for them to try to contact US directly. 
3.	The intake form is designed for us to be able to contact them and sends their information to the correct person via zip code look up.
4.	This is also where there should be a way for them to find someone aka: “Find a design pro” which also goes by zip code, but yes, just displays the reps name, phone # and email address. 

a.	I don’t want to sound too disrespectful, but this is contact 101 is it not? 

5.	Where in the world is our 800# ?

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by eidetyler** [comment]
Our intent with this page from the beginning, based on Modern Shed's request, was to create more qualified leads, and less cold-calls. WE pulled the information off of this page directly in order to funnel your potential customers through that filter. 

And the "a. comment"  is certainly taken as disrespectful - we've designed hundreds of contact pages, and adjusted this one based on what you asked for specifically. If you want the other content on there, please just ask - we're happy to figure out how it could be added. 

Ultimately, we just want to make sure that we're not taking away from the information capture opportunity by providing other outlets for people to reach out directly.

**Comment by ModernShed** [comment]
Tyler. Our phone # and mailing address MUST be on the contact page as it is now. The Find a Design Pro MUST be on the contact page as it is on our current site. I don’t see how this affects nor do I see where or how the site creates more qualified leads. I mean no disrespect, but thought it is obvious to include a phone # on a contact page and wrong of me to assume.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by eidetyler** [comment]
We'll find a good spot for it to get added. We may also want to look to add it to the footer as well? I'll check in with Caity and we'll go from there.

**Comment by ModernShed** [comment]
Yes, and thank you.

 

With Warmest Regards,

 

Tim Vack

GM

Modern-Shed, Inc.

D: 206.919.6599 | TF: 800-261-7282 xt 700

 <http://www.modern-shed.com/> www.modern-shed.com

**Comment by ckillorin** [comment]
@ModernShed -

- Add in contact info: we'll incorporate this somewhere on the page

- Find a Dealer: we'll also find a place to incorporate a link to this page somewhere on the contact page

- Update mandatory fields: Adding new required fields from what we had originally agreed upon is a slightly more complicated thing to update on the form but we're going to work on it. The only issue is, with a dynamic form that updates options depending on level of interest, we need to make sure that required fields are only showing up when the right level of interest is selected. Just want to be transparent about this + not commit to it being fully functional for this launch.
